
name: "CI"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: "Tests"

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3", "3.4"]
        sidekiq: ["~> 6", "~> 7"]

    env:
      SIDEKIQ_VERSION: "${{ matrix.sidekiq }}"

    services:
      redis:
        image: "redis"
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: "Setup ChromeDriver"
        uses: "nanasess/setup-chromedriver@v2"

      - name: "Run specs"
        run: "CAPYBARA_DRIVER=selenium_chrome_headless bundle exec rspec --format progress"

      - name: "Run Rubocop"
        run: "bundle exec rubocop"

      - name: "Upload artifacts"
        if: matrix.ruby == '3.4' && matrix.sidekiq == '~> 7'
        uses: "actions/upload-artifact@v4"
        with:
          name: "coverage-artifacts"
          path: "${{github.workspace}}/coverage/coverage.json"
          retention-days: 1

  coverage:
    name: "Report coverage to Code Climate"
    runs-on: "ubuntu-20.04"
    needs: "tests"
    if: success() && github.ref == 'refs/heads/master'
    env:
      CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Download coverage artifacts from test job"
        uses: "actions/download-artifact@v4"
        with:
          name: "coverage-artifacts"
      - uses: "paambaati/codeclimate-action@v3.2.0"
        with:
          coverageLocations: "coverage.json:simplecov"
