name: "CI"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: "Tests"

    strategy:
      fail-fast: false
      matrix:
        sidekiq: ['= 7', '= 7.3']
        ruby: ['3.0.0', '3.1', '3.2', '3.3', '3.4']
        rack: ['~> 2.2', '>= 3.1.0']
        include:
          # Sidekiq < 7 is only compatible with Rack ~> 2.0
          - sidekiq: '= 6.5'
            ruby: '3.2'
            rack: '~> 2.0'
          - sidekiq: '= 6.5'
            ruby: '3.3'
            rack: '~> 2.0'
          - sidekiq: '= 6.5'
            ruby: '3.4'
            rack: '~> 2.0'
          # Sidekiq 8 is only compatible with Ruby >= 3.2 and Rack >= 3.1
          - sidekiq: '= 8'
            ruby: '3.2'
            rack: '>= 3.1.0'
          - sidekiq: '= 8'
            ruby: '3.3'
            rack: '>= 3.1.0'
          - sidekiq: '= 8'
            ruby: '3.4'
            rack: '>= 3.1.0'

    env:
      RACK_VERSION: "${{ matrix.rack }}"
      SIDEKIQ_VERSION: "${{ matrix.sidekiq }}"

    services:
      redis:
        image: "redis"
        ports: ["6379:6379"]

    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: "Install dependencies"
        run: bundle install

      - name: "Setup ChromeDriver"
        uses: "nanasess/setup-chromedriver@v2"

      - name: "Run specs"
        run: "CAPYBARA_DRIVER=selenium_chrome_headless bundle exec rspec --format progress"

      - name: "Run Rubocop"
        run: "bundle exec rubocop"

      - name: "Upload coverage to Qlty"
        if: matrix.ruby == '3.4' && matrix.sidekiq == '= 7' && matrix.rack == '>= 3.1.0'
        uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: coverage/.resultset.json
